"""Multi-station market trend comparison report generator.

Reads CSV produced by fetch_markets.py and produces a Markdown report
covering per-station category trend leaders, cross-station recurring
categories, and aggregate price/sale/search indices.
"""
import argparse
import csv
import re
import sys
from collections import defaultdict, Counter
from pathlib import Path


def safe_float(s, default=0.0):
    if s is None:
        return default
    if isinstance(s, (int, float)):
        return float(s)
    s = str(s).strip().rstrip("%")
    s = re.sub(r"[,$¥€£￥]", "", s)
    try:
        return float(s) if s and s != "-9999" else default
    except (ValueError, TypeError):
        return default


def load_rows(path):
    with Path(path).open(encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def top_per_station(rows, n=10):
    sections = []
    by_station = defaultdict(list)
    for r in rows:
        by_station[r["station"]].append(r)
    for st in sorted(by_station.keys()):
        items = sorted(by_station[st],
                       key=lambda r: -safe_float(r.get("sale_show")))
        top = items[:n]
        if not top:
            continue
        lines = [f"### {st} ({len(items)} trend items)", "",
                 "| Rank | Category | Title | Sale | Price | Search |",
                 "|---|---|---|---|---|---|"]
        for i, r in enumerate(top, 1):
            lines.append(f"| {i} | {r.get('category_name','')} | "
                         f"{r.get('title','')[:40]} | "
                         f"{r.get('sale_show','')} | "
                         f"{r.get('price_show','')} | "
                         f"{r.get('search_show','')} |")
        sections.append("\n".join(lines))
    return "\n\n".join(sections) if sections else "_No data_"


def cross_station_categories(rows):
    by_cat = defaultdict(set)
    cat_name = {}
    for r in rows:
        cat = r.get("category_nodeId", "")
        if not cat:
            continue
        by_cat[cat].add(r["station"])
        cat_name[cat] = r.get("category_name", "")
    recurring = [(cid, sts) for cid, sts in by_cat.items() if len(sts) > 1]
    if not recurring:
        return "_No category appears in multiple stations_"
    recurring.sort(key=lambda x: -len(x[1]))
    lines = ["| Category | Stations | Count |", "|---|---|---|"]
    for cid, sts in recurring[:20]:
        lines.append(f"| {cat_name.get(cid, cid)} | {', '.join(sorted(sts))} | "
                     f"{len(sts)} |")
    return "\n".join(lines)


def category_price_index(rows):
    """Average sale_show index per (station, category)."""
    bucket = defaultdict(list)
    for r in rows:
        key = (r["station"], r.get("category_name", "?"))
        bucket[key].append(safe_float(r.get("sale_show")))
    if not bucket:
        return "_No numeric sale data_"
    lines = ["| Station | Category | Avg Sale | Items |", "|---|---|---|---|"]
    for (st, cat), vals in sorted(bucket.items()):
        avg = sum(vals) / len(vals) if vals else 0
        lines.append(f"| {st} | {cat} | {avg:.1f} | {len(vals)} |")
    return "\n".join(lines)


def station_summary(rows):
    by_st = defaultdict(int)
    sale_sum = defaultdict(float)
    for r in rows:
        by_st[r["station"]] += 1
        sale_sum[r["station"]] += safe_float(r.get("sale_show"))
    if not by_st:
        return "_No rows_"
    lines = ["| Station | Trend Items | Total Sale Index |", "|---|---|---|"]
    for st in sorted(by_st.keys()):
        lines.append(f"| {st} | {by_st[st]} | {sale_sum[st]:.0f} |")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--markets", required=True, help="CSV from fetch_markets.py")
    p.add_argument("--out-md", required=True, help="Markdown report path")
    args = p.parse_args()

    rows = load_rows(args.markets)
    stations = sorted({r["station"] for r in rows})
    sample = len(rows)

    report = f"""# sorftime 多站点选市场趋势对比报告

> Auto-generated by `analyze.py`. Based on `marketTrendChartData` per
> category per station (free-tier scraping).

**抓取时间**: {__import__('datetime').datetime.now().strftime('%Y-%m-%d')} |
**样本量**: {sample} 条 trend items | **站点数**: {len(stations)} |
**站点列表**: {", ".join(stations) or "无"}

> sorftime 选市场 (`/home/choosemarketblock`) 是多 tab 复杂面板，免费层
> 主要暴露 `marketTrendChartData`（20 条/触发）— 价格/销量/搜索指数趋势。
> 其他面板（统计、榜单、品牌矩阵）需要更深入的 UI 交互，本报告不含。

---

## 一、各站点 Top 10 趋势商品（按 sale_show）

{top_per_station(rows, 10)}

---

## 二、跨站点重复类目

{cross_station_categories(rows)}

---

## 三、各站点 × 类目 销量指数汇总

{category_price_index(rows)}

---

## 四、站点趋势样本总览

{station_summary(rows)}

---

## 五、行动建议（模板）

| 角色 | 建议 |
|---|---|
| **跨境新手** | _（看高 sale_show 但 search_show 较低的类目 — 需求强竞争小）_ |
| **成熟品牌** | _（看跨站重复类目的销售指数对比，找差异化市场）_ |

---

## 报告复现命令

```bash
python <path-to-skill>/scripts/fetch_markets.py --station US,JP,GB \\
    --categories baby-products,beauty,home-kitchen \\
    --out <out-dir>/markets_by_station.csv
python <path-to-skill>/scripts/analyze.py \\
    --markets <out-dir>/markets_by_station.csv \\
    --out-md <report>.md
```

`<path-to-skill>` = `.claude/skills/sorftime-market` for project install.
"""
    out = Path(args.out_md)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")
    print(f"wrote report → {out}")


if __name__ == "__main__":
    main()
