"""Multi-station keyword state summary report.

Reads the state-summary CSV from fetch_keywords.py and produces a
Markdown report describing which stations have populated data and
which need further UI interaction.
"""
import argparse
import csv
import sys
from pathlib import Path


def load_rows(path):
    with Path(path).open(encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--keywords", required=True, help="CSV from fetch_keywords.py")
    p.add_argument("--out-md", required=True, help="Markdown report path")
    args = p.parse_args()

    rows = load_rows(args.keywords)
    stations = sorted({r["station"] for r in rows if r.get("station")})

    by_station_lines = ["| Station | VM Found | Loading | Data Rows | Total | Cols | Screen Select |",
                        "|---|---|---|---|---|---|---|"]
    for r in rows:
        ss = (r.get("screen_select") or "")[:40]
        by_station_lines.append(
            f"| {r.get('station','')} | {r.get('vm_found','')} | "
            f"{r.get('loading','')} | {r.get('table_data_len',0)} | "
            f"{r.get('table_total_count',0)} | {r.get('column_count',0)} | "
            f"`{ss}` |"
        )

    populated = [r for r in rows if int(r.get("table_data_len", 0) or 0) > 0]
    unpopulated = [r for r in rows if int(r.get("table_data_len", 0) or 0) == 0]

    report = f"""# sorftime 多站点关键词页面状态报告

> Auto-generated by `analyze.py`. Diagnostic report —
> 选关键词 page requires category dialog interaction to populate data.

**抓取时间**: {__import__('datetime').datetime.now().strftime('%Y-%m-%d')} |
**站点数**: {len(stations)} |
**有数据站点**: {len(populated)} / {len(rows)}

> sorftime 选关键词 (`/home/choosekeyword`) 是筛选门控的关键词榜单。
> 与 bestseller/product 不同，此页面要求用户显式打开「类目」对话框并选择类目后，
> `side-Keyword.keywordData.List` 才会填充。本报告记录每站点的 VM 状态。

---

## 一、各站点 VM 状态

{chr(10).join(by_station_lines)}

---

## 二、已填充数据站点

"""
    if populated:
        report += "| Station | Rows | Total | Sample |\n|---|---|---|---|\n"
        for r in populated:
            sample = (r.get("sample_row_json") or "")[:80]
            report += f"| {r['station']} | {r['table_data_len']} | {r['table_total_count']} | `{sample}` |\n"
    else:
        report += "_无站点有数据 — 所有站点均需手动选择类目_\n"

    report += f"""

---

## 三、未填充数据站点

"""
    if unpopulated:
        report += "| Station | VM Found | Reason |\n|---|---|---|\n"
        for r in unpopulated:
            reason = "VM not found" if r.get("vm_found") != "True" else "需手动开「类目」对话框"
            report += f"| {r.get('station','')} | {r.get('vm_found','')} | {reason} |\n"
    else:
        report += "_所有站点均已填充数据_\n"

    report += f"""

---

## 四、行动建议

| 场景 | 操作 |
|---|---|
| **本脚本捕获到数据** | 在浏览器同会话中，本站点的「类目」已选 — 可在 CSV 中查看 keyword rows |
| **本脚本未捕获数据** | 在 sorftime 页面手动打开「类目」对话框 → 选类目 → 关闭对话框 → 重跑 `fetch_keywords.py` |
| **想要全自动** | 需要 reverse-engineer 类目对话框的 Vue 组件 — 见 `references/api_notes.md` 的未完成调研 |

---

## 报告复现命令

```bash
python <path-to-skill>/scripts/fetch_keywords.py --station US,JP,GB \\
    --out <out-dir>/kw_state.csv
python <path-to-skill>/scripts/analyze.py \\
    --keywords <out-dir>/kw_state.csv \\
    --out-md <report>.md
```

`<path-to-skill>` = `.claude/skills/sorftime-keyword` for project install.
"""
    out = Path(args.out_md)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")
    print(f"wrote report → {out}")


if __name__ == "__main__":
    main()
