"""Multi-station seller page state summary report."""
import argparse
import csv
import sys
from pathlib import Path


def load_rows(path):
    with Path(path).open(encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--sellers", required=True, help="CSV from fetch_sellers.py")
    p.add_argument("--out-md", required=True, help="Markdown report path")
    args = p.parse_args()

    rows = load_rows(args.sellers)
    stations = sorted({r["station"] for r in rows if r.get("station")})

    by_station_lines = ["| Station | VM | Loading | Rows | Total | Cols | Screen Select |",
                        "|---|---|---|---|---|---|---|"]
    for r in rows:
        ss = (r.get("screen_select") or "")[:40]
        by_station_lines.append(
            f"| {r.get('station','')} | {r.get('vm_found','')} | "
            f"{r.get('loading','')} | {r.get('table_data_len',0)} | "
            f"{r.get('table_total_count',0)} | {r.get('column_count',0)} | "
            f"`{ss}` |"
        )

    populated = [r for r in rows if int(r.get("table_data_len", 0) or 0) > 0]
    unpopulated = [r for r in rows if int(r.get("table_data_len", 0) or 0) == 0]
    cols_sample = rows[0].get("column_props", "") if rows else ""

    report = f"""# sorftime 多站点卖家页面状态报告

> Auto-generated by `analyze.py`. Diagnostic report —
> 选卖家 page requires category dialog interaction to populate data.

**抓取时间**: {__import__('datetime').datetime.now().strftime('%Y-%m-%d')} |
**站点数**: {len(stations)} |
**有数据站点**: {len(populated)} / {len(rows)}

> sorftime 选卖家 (`/home/chooseseller`) 复用 keyword/brand 页面的 side-Keyword VM，
> 列模式与 brand 相同（11 列：Name, TopTypeName, SaleCount, AveragePrice,
> NewProductSaleCount, ProductCount, AvgComentCount, AvgScore,
> SaleCountPrevThree, BusySeason, CyclicalMarket）。
> 同样需要先手动选类目才能填充数据。

**列模式**: `{cols_sample}`

---

## 一、各站点 VM 状态

{chr(10).join(by_station_lines)}

---

## 二、已填充数据站点

"""
    if populated:
        report += "| Station | Rows | Total | Sample |\n|---|---|---|---|\n"
        for r in populated:
            sample = (r.get("sample_row_json") or "")[:80]
            report += f"| {r['station']} | {r['table_data_len']} | {r['table_total_count']} | `{sample}` |\n"
    else:
        report += "_无站点有数据 — 所有站点均需手动选择类目_\n"

    report += f"""

---

## 三、未填充数据站点

"""
    if unpopulated:
        report += "| Station | VM Found | Reason |\n|---|---|---|\n"
        for r in unpopulated:
            reason = "VM not found" if r.get("vm_found") != "True" else "需手动开「类目」对话框"
            report += f"| {r.get('station','')} | {r.get('vm_found','')} | {reason} |\n"
    else:
        report += "_所有站点均已填充数据_\n"

    report += f"""

---

## 四、行动建议

| 场景 | 操作 |
|---|---|
| **本脚本捕获到数据** | 在浏览器同会话中，本站点的「类目」已选 |
| **本脚本未捕获数据** | 在 sorftime 页面手动打开「类目」对话框 → 选类目 → 重跑 `fetch_sellers.py` |

---

## 报告复现命令

```bash
python <path-to-skill>/scripts/fetch_sellers.py --station US,JP,GB \\
    --out <out-dir>/seller_state.csv
python <path-to-skill>/scripts/analyze.py \\
    --sellers <out-dir>/seller_state.csv \\
    --out-md <report>.md
```

`<path-to-skill>` = `.claude/skills/sorftime-seller` for project install.
"""
    out = Path(args.out_md)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")
    print(f"wrote report → {out}")


if __name__ == "__main__":
    main()
